repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            tests/data
          )
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            tests/data
          )
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: 14b3e118cfc36fb87d8d9cbd1305a2238fd85868
    hooks:
      - id: cargo-check
      - id: clippy
