[package]
name = "git-wok"
description = "A multirepo management tool."
version = "1.5.0"
authors = ["Serge Matveenko <lig@countzero.co>"]
license = "MIT"
edition = "2024"
documentation = "https://git-wok.dev/"
homepage = "https://git-wok.dev/"
repository = "https://codeberg.org/wok/wok"

[[bin]]
name = "wok"
path = "src/bin/git_wok.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6.5"
git2 = { version = "0.21.0", features = ["https", "ssh"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"

[dev-dependencies]
assert_fs = "1.1.4"
pretty_assertions = "1.4.1"
rstest = "0.26.1"
shell-words = "1.1.1"
