clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

when:
  event:
    - push
  path:
    include: ["src/**", "tests/**", ".woodpecker/**", "Cargo.*"]

steps:
  test:
    image: rust:1
    commands:
      - cargo test
