clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      lfs: false
      recursive: false

when:
  event:
    - push
  path:
    include: ["src/**", "tests/**", ".woodpecker/**", "Cargo.*"]

steps:
  test:
    image: rust:1
    commands:
      - git config --global user.email 'ci@localhost'
      - git config --global user.name 'CI Test'
      - git config --global init.defaultBranch 'main'
      - git config --global --add safe.directory '*'
      - cargo test -- --test-threads=1
